### ISSUE TITLE
Permission and Ranks finalized

### ISSUE THREAD

**Issue by bassettmason** [Snowy-Peak-Systems/CodeMiners-Info#41]
Discuss and implement permissions and rank system

- [x] PlotLand ranks
- [x] Survival / Lobby ranks

**Comment by leviem1** [comment]
Need document outlining all permissions per rank as well as rank progress or to sit down and setup all of these permissions while on the phone. @bassettmason

**Comment by bassettmason** [comment]
after economy introduced we will finalize

**Comment by leviem1** [comment]
@bassettmason Can you send me whatever you have written down for the ranks we're gonna go with?

**Comment by bassettmason** [comment]
what we have for the ranks is in the google docs. What do we need to do for the automated rank system to close this out?

**Comment by leviem1** [comment]
I'm waiting on lobby/survival ranks and world permission enforcement. I should be able to do the world enforcement quickly.

I'm also realizing that though there's an option for the player's location for promotions, it won't enforce that the blocks placed/broken requirement was completed in that world. The requirement is satisfied just from the user visiting that world, so we will have to revise our promotion strategy. Here's a [list](https://github.com/Staartvin/Autorank-2/wiki/Requirements-&-Results#basic-requirements) of possible requirements. I'm thinking we could focus on mobs killed and players killed instead which may promote *both* minigames and survival simultaneously.

This plugin doesn't seem super geared towards non-linear ranks either, so we might also want to look for an alternative if we don't want to change our strategy.
