### ISSUE TITLE
Add town for trading/selling

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#45]
**Is your feature request related to a problem? Please describe.**
We need a trading system and only allowing trades between players does not allow for offline progress. Setting hard prices for materials influences the economy externally.

**Describe the solution you'd like**
A protected town below spawn to allow building of a store using buy/sell signs by claiming a plot.

**Describe alternatives you've considered**
Only allow special protection stone to be placed within a specific region under spawn.

**Additional context**
#35

**Comment by leviem1** [comment]
@bassettmason I think we should consider rolling this as our primary trading system, doing away with us setting the price of any currency by allowing players to create their own store that can run offline.

**Comment by bassettmason** [comment]
I agree lets let a natural system happen

**Comment by leviem1** [comment]
Going to keep this open as a separate idea in addition to the trade signs system we will implement as I don't think the two are dependent.
