### ISSUE TITLE
Discord Link Advertisement In-Server

### ISSUE THREAD

**Issue by bassettmason** [Snowy-Peak-Systems/CodeMiners-Info#47]
**Is your feature request related to a problem? Please describe.**
Get our MC server to advertise our Discord server for more community involvement

**Describe the solution you'd like**
in game pop up message that advertises the link to the discord server

**Describe alternatives you've considered**
any alternative would work for me

**Additional context**
the server has new role system where new members don't get student
(wait until after beta get rolling)

**Comment by leviem1** [comment]
Also waiting on #54
