### ISSUE TITLE
Update PlotSquared v5

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#48]
**Is your update request related to a problem? Please describe.**
None applicable

**Update Information**
 - Name: PlotSquared
 - Plugin Page: https://www.spigotmc.org/resources/plotsquared-v5.77506/

**Describe alternatives if applicable**
None applicable

**Comment by bassettmason** [comment]
sent them via discord

**Comment by bassettmason** [comment]
sent levi the 5.13.2
