### ISSUE TITLE
Update ChatControl Pro

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#49]
**Is your update request related to a problem? Please describe.**
There are some potential issues with using ViaVersion and ChatControl together with the current version, though I haven't seen issues in our server yet.

**Update Information**
 - Name: ChatControl Pro
 - Plugin Page: https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-1.10258/updates

**Describe alternatives (if applicable)**
None applicable

**Comment by bassettmason** [comment]
sent them via discord

**Comment by leviem1** [comment]
Had to update this due to 1.16.2 issues with the older version
