### ISSUE TITLE
Use NPCs for instructions in spawn

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#5]
**Is your feature request related to a problem? Please describe.**
The current spawn lacks clear direction and instructions for users.

**Describe the solution you'd like**
We can use the [Citizens](https://www.spigotmc.org/resources/citizens.13811/) plugin to explain rules to newbies.

**Describe alternatives you've considered**
This can be done independently or in coordination with a lobby redesign and [DeluxeMenus](https://www.spigotmc.org/resources/deluxemenus.11734/).

**Additional context**
Citizens plugin costs $10, but source code is free so we can self-compile.

**Comment by bassettmason** [comment]
10 bucks isn't that bad I need to look in to the the plugin and see if it could help us with more than one issue to see if it's worth it

**Comment by leviem1** [comment]
@bassettmason It's not, but we can pretty easily bypass too. Let me know.
