### ISSUE TITLE
Friend/Party System

### ISSUE THREAD

**Issue by Lightmagi** [Snowy-Peak-Systems/CodeMiners-Info#53]
**Is your feature request related to a problem? Please describe.**
NA

**Describe the solution you'd like**
A way for players to friend each other and create parties for events or game modes.

**Describe alternatives you've considered**
NA

**Additional context**
https://www.spigotmc.org/resources/friends-mc1-8-x-1-16-x-party-system.12063/

**Comment by leviem1** [comment]
Found a potential plugin (added to additional context above) but it has some limitations. We won't be able to let parties join games as a team as that would require the party plugin to work with each of our minigame plugins. That being said, players can still add and message "friends" and create chat "parties".

We also should probably be cautious about letting players tp to fellow party members as this might cause issues in minigames.

**Comment by bassettmason** [comment]
lets hold on this now.
