### ISSUE TITLE
Update MessageAnnouncer

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#54]
**Is your update request related to a problem? Please describe.**
MessageAnnouncer is incompatible with Minecraft 1.16.2.

**Update Information**
- Name: MessageAnnouncer
- Plugin Page: https://www.spigotmc.org/resources/messageannouncer.5408/

**Describe alternatives (if applicable)**
https://www.spigotmc.org/resources/announcementseverywhere-1-13-x-1-16-x.59510/
https://www.spigotmc.org/resources/%E2%99%A6-kixs-auto-announcer-%E2%99%A6-announcements-that-stand-out-1-12-1-16-x.50320/updates

**Comment by bassettmason** [comment]
are they updating soon?

**Comment by leviem1** [comment]
🤷🏻‍♂️
