### ISSUE TITLE
Nether and End portals not working

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#55]
**Describe the bug**
When entering an end or nether portal, you are never teleported.

**To Reproduce**
1. Build a portal in survival
2. Enter the portal
3. It doesn't teleport

**Expected behavior**
It should teleport you to the correct dimension

**Screenshots**
N/A

**Additional information**
 - World: survival, survival_nether, survival_the_end
 - Related Plugins: Multiverse-Core, Multiverse-NetherPortals

**Additional context**
Multiverse/Multiverse-NetherPortals#173

**Comment by bassettmason** [comment]
Just tested it nether does not work. Last night it did

**Comment by leviem1** [comment]
Used temporary work-around for now. It's a bug in the server software. Side effects of the work around are that there is now a nether and end world for our original lobby world.
