### ISSUE TITLE
Setup reward and referral system

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#64]
**Is your feature request related to a problem? Please describe.**
We have low server attendance.

**Describe the solution you'd like**
Give players money for inviting friends. Give players money for time spent in the server.

**Describe alternatives you've considered**
N/A

**Additional context**
Possibilities:
https://www.spigotmc.org/resources/rewardpro-daily-rewards-rank-reward-delivery-man.24346/
https://www.spigotmc.org/resources/time-is-money.12409/

**Comment by leviem1** [comment]
Will mark as completed, but will still need to install

**Comment by leviem1** [comment]
Plugin ended up crashing and being of poor quality. Currently looking into using [Referral](https://www.spigotmc.org/resources/referral-1-7-1-16.72219/) and Time is Money (above) as a replacement.

**Comment by leviem1** [comment]
**TODO**
- [ ] Setup Time Is Money
- [ ] Setup Referral

@bassettmason How much do we want to give and at what interval for play time? What should be the maximum per day?

**Comment by bassettmason** [comment]
the atm system that time is money has makes me want to implement the bounty system in survival
I asked for the server input for time is money payouts
after looking at the Referral plugin it seems we could do a pretty competition after 1 week who-ever has the most referrals wins a prize

**Comment by bassettmason** [comment]
every 30 mins get 50$ and have a max of 200 seems to be the consensus

**Comment by leviem1** [comment]
> we need to give them more reasons to spend money?

Agreed, they don't really care for the money right now. We have everything in place we'd need to make that happen, we just need to figure out how we should go about it.

> A custom item survival shop is my idea but it would need to be so they can't dupe or repair the items.

It's gonna be on us to make sure that there aren't any duplication glitches for the items we sell since those glitches usually occur in the vanilla minecraft code. The best we can do to make it "unrepairable" is to make the cost of repair something ridiculously high like "100 xp levels" or even "10,000 levels".

Nonetheless, this is not the thread for *this* discussion, so let's move this over to #70.

As for the prices, sounds good, I'll try to do it tonight!
