### ISSUE TITLE
SkyWars various issues

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#69]
**Describe the bug**
Players receive errors when teleporting to a location outside of a vanilla world on server start. Inventories are being wiped. High chances of something breaking anytime a change is made.

**To Reproduce**
Steps to reproduce the join issue:
1. Restart server
2. Join SkyWars
3. Leave SkyWars
4. See error and incorrect teleport location

Steps to reproduce the inventory issue:
1. Join SkyBlock
2. Join SkyWars from SkyBlock
3. Leave SkyWars
4. SkyBlock inventory is gone (might be transferred to lobby world)

**Expected behavior**
The player should be teleported to the correct location.

**Screenshots**
N/a

**Additional information**
 - World: Non-vanilla worlds
 - Related Plugins: [SkyWarsReloaded](https://www.spigotmc.org/resources/skywarsreloaded-updated-recoded-1-16-support-new-features-1-8x-1-16x.69436/)

**Additional context**
Will need to wait on an update from the developer. Current workaround is to run `/sw reload` after server restart.

**Comment by leviem1** [comment]
So, when we initially decided to implement SkyWars, we had originally attempted to use [Skywars X](https://www.spigotmc.org/resources/%E2%99%9B-skywars-x-%E2%99%9B-solo-teams-kits-cages-trails-mystery-box-parties.28120/), but due to many bugs it wasn't stable enough to run on our server. Since then, we've been using SkyWarsReloaded, but it's become apparent that the maintainers of this project are incapable of keeping up with its issues. Since we've switched, Skywars X has actually become much more stable and the ratings have greatly improved, so I believe it's time to switch back.

We did pay for Skywars X before we switched, so @bassettmason will have to send the updated jar file my way.

**Comment by bassettmason** [comment]
I sent you this already right?

**Comment by leviem1** [comment]
Yes, haven't gotten to it yet

**Comment by leviem1** [comment]
I think our current plugin has stabilized a lot the last few weeks. Will update the plugin and see what changes.

**Comment by leviem1** [comment]
Nope, these are very much still an issue. I've reported to the developer because I really don't want to migrate everything over, but will do if these issues aren't resolved in the next month.

lukasvdgaag/SkyWarsReloaded#2
lukasvdgaag/SkyWarsReloaded#3

**Comment by leviem1** [comment]
Still waiting on an update from current authors. They're aware of the issue. Might send some more pics their direction to encourage more investigation.
