### ISSUE TITLE
Add Anti-Cheat

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#71]
**Is your feature request related to a problem? Please describe.**
There are some players using x-ray, pvp, and fly hacks on our server.

**Describe the solution you'd like**
We should look into an automated anti-cheat solution.

**Describe alternatives you've considered**
We could also investigate establishing a moderator team.

**Additional context**
Possible option: [Spartan](https://www.spigotmc.org/resources/spartan-advanced-anti-cheat-hack-blocker.25638/)

**Comment by leviem1** [comment]
@bassettmason Opinion?

**Comment by bassettmason** [comment]
hmm how do moderator team usually work and how effective are anti-cheat solutions

**Comment by leviem1** [comment]
The reliability of any anti-cheats depends on the author. The linked plugin
is the best I could find. The biggest issue is some false positives, but
this plugin is supposed to be better at it. I don't imagine we would give
out punishments automatically with it, but it can help prevent some cheats
and log when it detects something suspicious.

A mod team would just be some players with a few extra tools for
investigating incidents. We'd have to manage them and confirm their
findings. Just a way of doing the same thing with manpower.

The only reason I bring it up is because we've had a recent report that I
can't verify the credibility on and I don't really feel like investigating
much. We could also just choose to let this go stale until there's more of
a need.

**Comment by bassettmason** [comment]
I want to move forward on the mod team lets do a 10 min meeting to setup candidates when-ever you have time.

**Comment by leviem1** [comment]
Gonna mark this as closed since we decided to go for the mod team, and we can reopen it if we need to in the future
