### ISSUE TITLE
Update ChatControl to 8.8.14

### ISSUE THREAD

**Issue by leviem1** [Snowy-Peak-Systems/CodeMiners-Info#72]
**Is your update request related to a problem? Please describe.**
I think this is related to the sign and join errors.

**Update Information**
Link: [ChatControl](https://www.spigotmc.org/resources/%E2%99%A3-chatcontrol-pro%E2%84%A2-format-and-filter-your-chat-1-7-10-1-16-3.10258/)
Dependencies: N/A

**Describe alternatives (if applicable)**
N/A

**Comment by bassettmason** [comment]
sent it

**Comment by leviem1** [comment]
God I hate this plugin. After fixing a few configs broken by the update, this is done. Not sure if this helps the join errors yet.
